export const driverRecords = [
  {
    slug: 'lewis-hamilton',
    name: 'Lewis Hamilton',
    title: 'Record-Breaking Standard',
    description: "Hamilton redefined modern consistency and qualifying speed across multiple regulation eras. His seven titles, 106 wins, 206 podiums, and 104 poles place him at or near the top of Formula One's major all-time lists.",
    titles: 7,
    wins: 106,
    podiums: 206,
    poles: 104,
    image_path: './assets/goat-hamilton-photo.jpg',
    image_alt: 'Lewis Hamilton at the 2024 Chinese Grand Prix',
    crop_class: 'crop-center',
    source_url: 'https://commons.wikimedia.org/wiki/File:Lewis_Hamilton_2024_Chinese_GP.jpg',
    display_order: 1
  },
  {
    slug: 'michael-schumacher',
    name: 'Michael Schumacher',
    title: 'Ferrari Dynasty Builder',
    description: "Schumacher turned Ferrari into the benchmark of the early 2000s, pairing relentless pace with technical feedback and physical preparation. His peak included five consecutive drivers' titles from 2000 to 2004.",
    titles: 7,
    wins: 91,
    podiums: 155,
    poles: 68,
    image_path: './assets/goat-schumacher-photo.jpg',
    image_alt: 'Michael Schumacher portrait at a Formula One event',
    crop_class: 'crop-top',
    source_url: 'https://commons.wikimedia.org/wiki/File:Michael_Schumacher_01_(sk).jpg',
    display_order: 2
  },
  {
    slug: 'ayrton-senna',
    name: 'Ayrton Senna',
    title: 'Qualifying and Wet-Weather Genius',
    description: "Senna's raw speed, Monaco mastery, and intensity made him a defining figure of F1. His 65 pole positions and 41 wins came in an era where qualifying bravery and manual precision were brutally exposed.",
    titles: 3,
    wins: 41,
    podiums: 80,
    poles: 65,
    image_path: './assets/goat-senna-photo.jpg',
    image_alt: 'Ayrton Senna in Formula One racing gear',
    crop_class: 'crop-center',
    source_url: 'https://commons.wikimedia.org/wiki/File:Ayrton_Senna_5.jpg',
    display_order: 3
  },
  {
    slug: 'juan-manuel-fangio',
    name: 'Juan Manuel Fangio',
    title: 'The Original Master',
    description: 'Fangio dominated the most dangerous early years of the championship. He won five titles with four different teams and took 24 victories from only 51 championship starts, an extraordinary strike rate.',
    titles: 5,
    wins: 24,
    podiums: 35,
    poles: 29,
    image_path: './assets/goat-fangio-photo.jpg',
    image_alt: 'Juan Manuel Fangio portrait from the early Formula One era',
    crop_class: 'crop-top',
    source_url: 'https://commons.wikimedia.org/wiki/File:Juan_Manuel_Fangio_(circa_1952).jpg',
    display_order: 4
  },
  {
    slug: 'alain-prost',
    name: 'Alain Prost',
    title: 'The Professor',
    description: "Prost made race management a weapon. His calm, calculated style delivered four championships, 51 wins, and 106 podiums while shaping one of F1's greatest rivalries with Senna.",
    titles: 4,
    wins: 51,
    podiums: 106,
    poles: 33,
    image_path: './assets/goat-prost-photo.jpg',
    image_alt: 'Alain Prost at the 1991 United States Grand Prix',
    crop_class: 'crop-center',
    source_url: 'https://commons.wikimedia.org/wiki/File:Alain_Prost_1991_United_States_GP.jpg',
    display_order: 5
  },
  {
    slug: 'max-verstappen',
    name: 'Max Verstappen',
    title: 'Modern Control and Attack',
    description: 'Verstappen became the reference of the current era through race pace, tyre control, and ruthless wheel-to-wheel execution. His 2023 season set new standards for sustained dominance.',
    titles: 4,
    wins: 71,
    podiums: 129,
    poles: 48,
    image_path: './assets/goat-verstappen-photo.jpg',
    image_alt: 'Max Verstappen driving at the 2022 Imola Grand Prix',
    crop_class: 'crop-center',
    source_url: 'https://commons.wikimedia.org/wiki/File:Max_Verstappen_2022.jpg',
    display_order: 6
  },
  {
    slug: 'sebastian-vettel',
    name: 'Sebastian Vettel',
    title: 'The Red Bull Era Architect',
    description: "Vettel's four straight championships showed elite qualifying, tire-sensitive race control, and complete trust in high-downforce machinery. His 2013 run remains one of the sport's great domination streaks.",
    titles: 4,
    wins: 53,
    podiums: 122,
    poles: 57,
    image_path: './assets/goat-vettel-photo.jpg',
    image_alt: 'Sebastian Vettel during Formula One testing in 2019',
    crop_class: 'crop-center',
    source_url: 'https://commons.wikimedia.org/wiki/File:Sebastian_Vettel-Ferrari-2019_(6).jpg',
    display_order: 7
  }
];
